### ISSUE TITLE
How use that?

### ISSUE THREAD

**Issue by pafurijaz** [edzop/bpyhullgen#1]
Hi installed the master add-on in my default path, but when I try to execute I get these errors in Blender, I want try the part for developing plates with my own design also trying to figure out how it works, but no way.

```
Traceback (most recent call last):
  File "/home/default/Software/Blender_dev_build/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/default/.config/blender/2.92/scripts/addons/bpyhullgen-master/__init__.py", line 50, in <module>
    from . import (
  File "/home/default/.config/blender/2.92/scripts/addons/bpyhullgen-master/genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "/home/default/.config/blender/2.92/scripts/addons/bpyhullgen-master/hullgen/xml_helper.py", line 5, in <module>
    from bpyhullgen.hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen'
```

**Comment by edzop** [comment]
Hello - Thanks for your question. I was able to identify and fix your problem. 

My install is:
`addons/bpyhullgen` 

Your install is:
`/addons/bpyhullgen-master`

To fix problem:
rename install directory `bpyhullgen-master` to `bpyhullgen`

Sorry for the delayed response.

**Comment by edzop** [comment]
Installation wiki updated to reflect submodules:
[bpyhullgen installation WIKI](https://github.com/edzop/bpyhullgen/wiki/Installation)

**Comment by pafurijaz** [comment]
Thanks I  will change the folder name, and soon I try this new update.

**Comment by pafurijaz** [comment]
Hi this renaming, doesn't make any changes I get the same error, I use Linux and the add-on dont' works even with renaming.

**Comment by edzop** [comment]
Hi thanks for trying again - can you post another traceback (console debug output) like you did in the first post?

**Comment by pafurijaz** [comment]
Hi I test today but always the same error my operating system is Linux OS
```
Traceback (most recent call last):
  File "/home/user-pf/Software/blender-2.93.0/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullgen/__init__.py", line 50, in <module>
    from . import (
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullgen/ui.py", line 23, in <module>
    from .hullgen import geometry_helper as geometry_helper
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullgen/hullgen/geometry_helper.py", line 26, in <module>
    from ..hullgen import curve_helper
  File "/home/user-pf/.config/blender/2.93/scripts/addons/bpyhullgen/hullgen/curve_helper.py", line 24, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullgen.bpyutils' (unknown location)
```

**Comment by edzop** [comment]
It looks like the [bpyutils](https://github.com/edzop/bpyutils) submodule isn't installed.

You can either manually get it from github and copy to `~/.config/blender/2.93/scripts/addons/bpyhullgen/bpyutils`

OR - the best way use the git submodule command:

`
cd ~/.config/blender/2.92/scripts/addons/bpyhullgen/
git submodule update --init
`
This should setup the bpyutils submodule automatically

**Comment by pafurijaz** [comment]
now works.. I hope to understand it.
