### ISSUE TITLE
Errors in import directories

### ISSUE THREAD

**Issue by BiDDo** [edzop/bpyhullgen#5]
bpyutils directory does not download with main bpyhullgen code .zip download.\\

Also corrected syntax in xml_helper, genui and hull_maker

See console log below of troubleshooting outcomes as I am not a python coder had to figure out the syntax error. 

Read prefs: C:\Users\RB\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\ui.py", line 23, in <module>
    from .hullgen import geometry_helper as geometry_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\geometry_helper.py", line 26, in <module>
    from ..hullgen import curve_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\curve_helper.py", line 24, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullgen-master.bpyutils' (unknown location)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\ui.py", line 23, in <module>
    from .hullgen import geometry_helper as geometry_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\geometry_helper.py", line 26, in <module>
    from ..hullgen import curve_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\curve_helper.py", line 24, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullgen-master.bpyutils' (unknown location)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\ui.py", line 23, in <module>
[bpyhullgen-master(fixed activation import code errors).zip](https://github.com/edzop/bpyhullgen/files/9844491/bpyhullgen-master.fixed.activation.import.code.errors.zip)

    from .hullgen import geometry_helper as geometry_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\geometry_helper.py", line 26, in <module>
    from ..hullgen import curve_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\curve_helper.py", line 24, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullgen-master.bpyutils' (unknown location)

Modules Installed () from 'C:\\Users\\RB\\Downloads\\bpyhullgen-master\\__init__.py' into 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\ui.py", line 23, in <module>
    from .hullgen import geometry_helper as geometry_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\geometry_helper.py", line 26, in <module>
    from ..hullgen import curve_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\curve_helper.py", line 24, in <module>
    from ..bpyutils import bpy_helper
ImportError: cannot import name 'bpy_helper' from 'bpyhullgen-master.bpyutils' (unknown location)

fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\genui.py'
Modules Installed () from 'C:\\Users\\RB\\Downloads\\bpyhullgen-master\\genui.py' into 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\genui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\genui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\render_tests.py'
Modules Installed () from 'C:\\Users\\RB\\Downloads\\bpyhullgen-master\\render_tests.py' into 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\genui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\render_tests.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\genui.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\render_tests.py'
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons\\ui.py'
Modules Installed () from 'C:\\Users\\RB\\Downloads\\bpyhullgen-master\\ui.py' into 'C:\\Users\\RB\\AppData\\Roaming\\Blender Foundation\\Blender\\3.3\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from bpyhullgen.hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'bpyhullgen-master'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5
    from bpyhullgen-master.hullgen import hull_maker
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5
    from bpyhullgen-master.hullgen import hull_maker
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5
    from bpyhullgen-master.hullgen import hull_maker
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 6
    from bpyhullgen-master.hullgen import chine_helper
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 6
    from bpyhullgen-master.hullgen import chine_helper
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 6
    from bpyhullgen-master.hullgen import chine_helper
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 6
    from bpyhullgen-master.hullgen import chine_helper
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 6
    from .hullgen import chine_helperfrom bpyhullgen-master.hullgen import keel_helper
                                          ^^^^^^^^^^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from .hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen-master.hullgen.hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from hullgen import hull_maker
ModuleNotFoundError: No module named 'hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from hullgen import hull_maker
ModuleNotFoundError: No module named 'hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from .hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen-master.hullgen.hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5
    from bpyhullgen-master.hullgen import hull_maker
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 35
    from bpyhullgen-master.bpyutils import bpy_helper
                   ^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from bpyhullgen.hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from bpyhullgen.hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from bpyhullgen.hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from .hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen-master.hullgen.hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    import hull_maker
ModuleNotFoundError: No module named 'hull_maker'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from .hullgen import hull_maker
ModuleNotFoundError: No module named 'bpyhullgen-master.hullgen.hullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5
    from import hull_maker
         ^^^^^^
SyntaxError: invalid syntax

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from . import hull_maker
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\hull_maker.py", line 33, in <module>
    from bpyhullgen.hullgen import prop_helper
ModuleNotFoundError: No module named 'bpyhullgen'

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\__init__.py", line 50, in <module>
    from . import (
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\genui.py", line 34, in <module>
    from .hullgen import xml_helper as xml_helper
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\xml_helper.py", line 5, in <module>
    from . import hull_maker
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\addons\bpyhullgen-master\hullgen\hull_maker.py", line 33, in <module>
    from bpyhullgen.hullgen import prop_helper
ModuleNotFoundError: No module named 'bpyhullgen'

**Comment by albrei43** [comment]
I had the same Problem. I solved it an now I feel a little bit stupid as the problem is quite trivieal. For other blender users that do know nothing about git: bpyutils and everything else, that is missing, is in a Git-Submodule. As discribed here https://github.com/edzop/bpyhullgen/wiki/Installation
I Followed this installation process and everything worked. Typical case of RTFM ;-)

cheers
